webtalk_init -webtalk_dir C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\Exercise5\\exercise5\\exercise5.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "on maj 6 10:40:04 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "jmk8nkq096mb5sncoiiafee3k1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1430832919093" -context "sdk\\\\hardware/1430832919093"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1430832919093"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1430832919093"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1430832919093"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1430832919093"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1430832919093"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1430832919093"
webtalk_add_data -client sdk -key uid -value "1430832937498" -context "sdk\\\\bsp/1430832937498"
webtalk_add_data -client sdk -key hwid -value "1430832919093" -context "sdk\\\\bsp/1430832937498"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1430832937498"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1430832937498"
webtalk_add_data -client sdk -key uid -value "1430833132431" -context "sdk\\\\application/1430833132431"
webtalk_add_data -client sdk -key hwid -value "1430832919093" -context "sdk\\\\application/1430833132431"
webtalk_add_data -client sdk -key bspid -value "1430832937498" -context "sdk\\\\application/1430833132431"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1430833132431"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1430833132431"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1430833132431"
webtalk_transmit -clientid 66057752 -regid "" -xml C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\Exercise5\\exercise5\\exercise5.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\Exercise5\\exercise5\\exercise5.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\Exercise5\\exercise5\\exercise5.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
