// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _MotorCtrl_pwmThread_HH_
#define _MotorCtrl_pwmThread_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct MotorCtrl_pwmThread : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<10> > pwmR;
    sc_in< sc_lv<10> > pwmL;
    sc_in< sc_logic > Direction;
    sc_out< sc_logic > EN1;
    sc_out< sc_logic > EN1_ap_vld;
    sc_out< sc_logic > EN2;
    sc_out< sc_logic > EN2_ap_vld;
    sc_out< sc_logic > DIR1;
    sc_out< sc_logic > DIR1_ap_vld;
    sc_out< sc_logic > DIR2;
    sc_out< sc_logic > DIR2_ap_vld;
    sc_in< sc_lv<10> > MotorCtrl_pwmCount_V_i;
    sc_out< sc_lv<10> > MotorCtrl_pwmCount_V_o;
    sc_out< sc_logic > MotorCtrl_pwmCount_V_o_ap_vld;
    sc_out< sc_logic > MotorCtrl_DIR;
    sc_out< sc_logic > MotorCtrl_DIR_ap_vld;
    sc_in< sc_lv<1> > MotorCtrl_pwmClock_V;


    // Module declarations
    MotorCtrl_pwmThread(sc_module_name name);
    SC_HAS_PROCESS(MotorCtrl_pwmThread);

    ~MotorCtrl_pwmThread();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > MotorCtrl_pwmClock_V_read_read_fu_108_p2;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_34;
    sc_signal< sc_lv<10> > MotorCtrl_pwmCount_V_assign_fu_188_p2;
    sc_signal< sc_lv<1> > tmp_2_fu_195_p2;
    sc_signal< sc_lv<1> > tmp_3_fu_201_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< bool > ap_sig_bdd_42;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st2_fsm_1;
    static const sc_lv<3> ap_ST_st3_fsm_2;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<10> ap_const_lv10_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_DIR1();
    void thread_DIR1_ap_vld();
    void thread_DIR2();
    void thread_DIR2_ap_vld();
    void thread_EN1();
    void thread_EN1_ap_vld();
    void thread_EN2();
    void thread_EN2_ap_vld();
    void thread_MotorCtrl_DIR();
    void thread_MotorCtrl_DIR_ap_vld();
    void thread_MotorCtrl_pwmClock_V_read_read_fu_108_p2();
    void thread_MotorCtrl_pwmCount_V_assign_fu_188_p2();
    void thread_MotorCtrl_pwmCount_V_o();
    void thread_MotorCtrl_pwmCount_V_o_ap_vld();
    void thread_ap_sig_bdd_34();
    void thread_ap_sig_bdd_42();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_tmp_2_fu_195_p2();
    void thread_tmp_3_fu_201_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
