webtalk_init -webtalk_dir C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\Exercise2\\Exercise3\\exercise3\\exercise3.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "ma maj 18 10:19:46 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211042119_0_0_130" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "gk6fev9ta99f3uc746mk6tkvdn" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_14" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU       Q 820  @ 1.73GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1729 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key date_generated -value "ma maj 18 10:19:39 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ggj779mbejtig3vv3no0mkts2a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_13" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1431931346062" -context "sdk\\\\hardware/1431931346062"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1431931346062"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1431931346062"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1431931346062"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1431931346062"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1431931346062"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1431931346062"
webtalk_transmit -clientid 2020675059 -regid "211042119_0_0_130" -xml C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\Exercise2\\Exercise3\\exercise3\\exercise3.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\Exercise2\\Exercise3\\exercise3\\exercise3.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\Exercise2\\Exercise3\\exercise3\\exercise3.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
