// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="yuv_filter,hls_ip_2014_4,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.748500,HLS_SYN_LAT=2353224,HLS_SYN_TPT=none,HLS_SYN_MEM=7200,HLS_SYN_DSP=15,HLS_SYN_FF=919,HLS_SYN_LUT=1305}" *)

module yuv_filter (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_channels_ch1_address0,
        in_channels_ch1_ce0,
        in_channels_ch1_q0,
        in_channels_ch2_address0,
        in_channels_ch2_ce0,
        in_channels_ch2_q0,
        in_channels_ch3_address0,
        in_channels_ch3_ce0,
        in_channels_ch3_q0,
        in_width,
        in_height,
        out_channels_ch1_address0,
        out_channels_ch1_ce0,
        out_channels_ch1_we0,
        out_channels_ch1_d0,
        out_channels_ch2_address0,
        out_channels_ch2_ce0,
        out_channels_ch2_we0,
        out_channels_ch2_d0,
        out_channels_ch3_address0,
        out_channels_ch3_ce0,
        out_channels_ch3_we0,
        out_channels_ch3_d0,
        out_width,
        out_width_ap_vld,
        out_height,
        out_height_ap_vld,
        Y_scale,
        U_scale,
        V_scale
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 6'b1;
parameter    ap_ST_st2_fsm_1 = 6'b10;
parameter    ap_ST_st3_fsm_2 = 6'b100;
parameter    ap_ST_st4_fsm_3 = 6'b1000;
parameter    ap_ST_st5_fsm_4 = 6'b10000;
parameter    ap_ST_st6_fsm_5 = 6'b100000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [21:0] in_channels_ch1_address0;
output   in_channels_ch1_ce0;
input  [7:0] in_channels_ch1_q0;
output  [21:0] in_channels_ch2_address0;
output   in_channels_ch2_ce0;
input  [7:0] in_channels_ch2_q0;
output  [21:0] in_channels_ch3_address0;
output   in_channels_ch3_ce0;
input  [7:0] in_channels_ch3_q0;
input  [15:0] in_width;
input  [15:0] in_height;
output  [21:0] out_channels_ch1_address0;
output   out_channels_ch1_ce0;
output   out_channels_ch1_we0;
output  [7:0] out_channels_ch1_d0;
output  [21:0] out_channels_ch2_address0;
output   out_channels_ch2_ce0;
output   out_channels_ch2_we0;
output  [7:0] out_channels_ch2_d0;
output  [21:0] out_channels_ch3_address0;
output   out_channels_ch3_ce0;
output   out_channels_ch3_we0;
output  [7:0] out_channels_ch3_d0;
output  [15:0] out_width;
output   out_width_ap_vld;
output  [15:0] out_height;
output   out_height_ap_vld;
input  [7:0] Y_scale;
input  [7:0] U_scale;
input  [7:0] V_scale;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_channels_ch1_ce0;
reg in_channels_ch2_ce0;
reg in_channels_ch3_ce0;
reg out_channels_ch1_ce0;
reg out_channels_ch1_we0;
reg out_channels_ch2_ce0;
reg out_channels_ch2_we0;
reg out_channels_ch3_ce0;
reg out_channels_ch3_we0;
reg out_width_ap_vld;
reg out_height_ap_vld;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm = 6'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [15:0] p_yuv_width_reg_204;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_91;
wire    grp_yuv_filter_rgb2yuv_fu_115_ap_done;
reg   [15:0] p_yuv_height_reg_209;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_106;
reg   [15:0] p_scale_width_reg_229;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_119;
wire    grp_yuv_filter_yuv_scale_fu_150_ap_done;
reg   [15:0] p_scale_height_reg_234;
reg   [21:0] p_yuv_channels_ch1_address0;
reg    p_yuv_channels_ch1_ce0;
reg    p_yuv_channels_ch1_we0;
wire   [7:0] p_yuv_channels_ch1_d0;
wire   [7:0] p_yuv_channels_ch1_q0;
reg   [21:0] p_yuv_channels_ch2_address0;
reg    p_yuv_channels_ch2_ce0;
reg    p_yuv_channels_ch2_we0;
wire   [7:0] p_yuv_channels_ch2_d0;
wire   [7:0] p_yuv_channels_ch2_q0;
reg   [21:0] p_yuv_channels_ch3_address0;
reg    p_yuv_channels_ch3_ce0;
reg    p_yuv_channels_ch3_we0;
wire   [7:0] p_yuv_channels_ch3_d0;
wire   [7:0] p_yuv_channels_ch3_q0;
reg   [21:0] p_scale_channels_ch1_address0;
reg    p_scale_channels_ch1_ce0;
reg    p_scale_channels_ch1_we0;
wire   [7:0] p_scale_channels_ch1_d0;
wire   [7:0] p_scale_channels_ch1_q0;
reg   [21:0] p_scale_channels_ch2_address0;
reg    p_scale_channels_ch2_ce0;
reg    p_scale_channels_ch2_we0;
wire   [7:0] p_scale_channels_ch2_d0;
wire   [7:0] p_scale_channels_ch2_q0;
reg   [21:0] p_scale_channels_ch3_address0;
reg    p_scale_channels_ch3_ce0;
reg    p_scale_channels_ch3_we0;
wire   [7:0] p_scale_channels_ch3_d0;
wire   [7:0] p_scale_channels_ch3_q0;
wire    grp_yuv_filter_rgb2yuv_fu_115_ap_start;
wire    grp_yuv_filter_rgb2yuv_fu_115_ap_idle;
wire    grp_yuv_filter_rgb2yuv_fu_115_ap_ready;
wire   [21:0] grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_address0;
wire    grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_ce0;
wire   [7:0] grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_q0;
wire   [21:0] grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_address0;
wire    grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_ce0;
wire   [7:0] grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_q0;
wire   [21:0] grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_address0;
wire    grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_ce0;
wire   [7:0] grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_q0;
wire   [15:0] grp_yuv_filter_rgb2yuv_fu_115_in_width_read;
wire   [15:0] grp_yuv_filter_rgb2yuv_fu_115_in_height_read;
wire   [21:0] grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_address0;
wire    grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_ce0;
wire    grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_we0;
wire   [7:0] grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_d0;
wire   [21:0] grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_address0;
wire    grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_ce0;
wire    grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_we0;
wire   [7:0] grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_d0;
wire   [21:0] grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_address0;
wire    grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_ce0;
wire    grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_we0;
wire   [7:0] grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_d0;
wire   [15:0] grp_yuv_filter_rgb2yuv_fu_115_ap_return_0;
wire   [15:0] grp_yuv_filter_rgb2yuv_fu_115_ap_return_1;
wire    grp_yuv_filter_yuv2rgb_fu_135_ap_start;
wire    grp_yuv_filter_yuv2rgb_fu_135_ap_done;
wire    grp_yuv_filter_yuv2rgb_fu_135_ap_idle;
wire    grp_yuv_filter_yuv2rgb_fu_135_ap_ready;
wire   [21:0] grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_address0;
wire    grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_ce0;
wire   [7:0] grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_q0;
wire   [21:0] grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_address0;
wire    grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_ce0;
wire   [7:0] grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_q0;
wire   [21:0] grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_address0;
wire    grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_ce0;
wire   [7:0] grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_q0;
wire   [15:0] grp_yuv_filter_yuv2rgb_fu_135_in_width_read;
wire   [15:0] grp_yuv_filter_yuv2rgb_fu_135_in_height_read;
wire   [21:0] grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_address0;
wire    grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_ce0;
wire    grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_we0;
wire   [7:0] grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_d0;
wire   [21:0] grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_address0;
wire    grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_ce0;
wire    grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_we0;
wire   [7:0] grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_d0;
wire   [21:0] grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_address0;
wire    grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_ce0;
wire    grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_we0;
wire   [7:0] grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_d0;
wire   [15:0] grp_yuv_filter_yuv2rgb_fu_135_ap_return_0;
wire   [15:0] grp_yuv_filter_yuv2rgb_fu_135_ap_return_1;
wire    grp_yuv_filter_yuv_scale_fu_150_ap_start;
wire    grp_yuv_filter_yuv_scale_fu_150_ap_idle;
wire    grp_yuv_filter_yuv_scale_fu_150_ap_ready;
wire   [21:0] grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_address0;
wire    grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_ce0;
wire   [7:0] grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_q0;
wire   [21:0] grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_address0;
wire    grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_ce0;
wire   [7:0] grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_q0;
wire   [21:0] grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_address0;
wire    grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_ce0;
wire   [7:0] grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_q0;
wire   [15:0] grp_yuv_filter_yuv_scale_fu_150_in_width_read;
wire   [15:0] grp_yuv_filter_yuv_scale_fu_150_in_height_read;
wire   [21:0] grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_address0;
wire    grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_ce0;
wire    grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_we0;
wire   [7:0] grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_d0;
wire   [21:0] grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_address0;
wire    grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_ce0;
wire    grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_we0;
wire   [7:0] grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_d0;
wire   [21:0] grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_address0;
wire    grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_ce0;
wire    grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_we0;
wire   [7:0] grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_d0;
wire   [7:0] grp_yuv_filter_yuv_scale_fu_150_Y_scale;
wire   [7:0] grp_yuv_filter_yuv_scale_fu_150_U_scale;
wire   [7:0] grp_yuv_filter_yuv_scale_fu_150_V_scale;
wire   [15:0] grp_yuv_filter_yuv_scale_fu_150_ap_return_0;
wire   [15:0] grp_yuv_filter_yuv_scale_fu_150_ap_return_1;
reg    grp_yuv_filter_rgb2yuv_fu_115_ap_start_ap_start_reg = 1'b0;
reg    grp_yuv_filter_yuv2rgb_fu_135_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_285;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_292;
reg    grp_yuv_filter_yuv_scale_fu_150_ap_start_ap_start_reg = 1'b0;
reg   [5:0] ap_NS_fsm;


yuv_filter_p_yuv_channels_ch1 #(
    .DataWidth( 8 ),
    .AddressRange( 2457600 ),
    .AddressWidth( 22 ))
p_yuv_channels_ch1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( p_yuv_channels_ch1_address0 ),
    .ce0( p_yuv_channels_ch1_ce0 ),
    .we0( p_yuv_channels_ch1_we0 ),
    .d0( p_yuv_channels_ch1_d0 ),
    .q0( p_yuv_channels_ch1_q0 )
);

yuv_filter_p_yuv_channels_ch1 #(
    .DataWidth( 8 ),
    .AddressRange( 2457600 ),
    .AddressWidth( 22 ))
p_yuv_channels_ch2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( p_yuv_channels_ch2_address0 ),
    .ce0( p_yuv_channels_ch2_ce0 ),
    .we0( p_yuv_channels_ch2_we0 ),
    .d0( p_yuv_channels_ch2_d0 ),
    .q0( p_yuv_channels_ch2_q0 )
);

yuv_filter_p_yuv_channels_ch1 #(
    .DataWidth( 8 ),
    .AddressRange( 2457600 ),
    .AddressWidth( 22 ))
p_yuv_channels_ch3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( p_yuv_channels_ch3_address0 ),
    .ce0( p_yuv_channels_ch3_ce0 ),
    .we0( p_yuv_channels_ch3_we0 ),
    .d0( p_yuv_channels_ch3_d0 ),
    .q0( p_yuv_channels_ch3_q0 )
);

yuv_filter_p_yuv_channels_ch1 #(
    .DataWidth( 8 ),
    .AddressRange( 2457600 ),
    .AddressWidth( 22 ))
p_scale_channels_ch1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( p_scale_channels_ch1_address0 ),
    .ce0( p_scale_channels_ch1_ce0 ),
    .we0( p_scale_channels_ch1_we0 ),
    .d0( p_scale_channels_ch1_d0 ),
    .q0( p_scale_channels_ch1_q0 )
);

yuv_filter_p_yuv_channels_ch1 #(
    .DataWidth( 8 ),
    .AddressRange( 2457600 ),
    .AddressWidth( 22 ))
p_scale_channels_ch2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( p_scale_channels_ch2_address0 ),
    .ce0( p_scale_channels_ch2_ce0 ),
    .we0( p_scale_channels_ch2_we0 ),
    .d0( p_scale_channels_ch2_d0 ),
    .q0( p_scale_channels_ch2_q0 )
);

yuv_filter_p_yuv_channels_ch1 #(
    .DataWidth( 8 ),
    .AddressRange( 2457600 ),
    .AddressWidth( 22 ))
p_scale_channels_ch3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( p_scale_channels_ch3_address0 ),
    .ce0( p_scale_channels_ch3_ce0 ),
    .we0( p_scale_channels_ch3_we0 ),
    .d0( p_scale_channels_ch3_d0 ),
    .q0( p_scale_channels_ch3_q0 )
);

yuv_filter_rgb2yuv grp_yuv_filter_rgb2yuv_fu_115(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_yuv_filter_rgb2yuv_fu_115_ap_start ),
    .ap_done( grp_yuv_filter_rgb2yuv_fu_115_ap_done ),
    .ap_idle( grp_yuv_filter_rgb2yuv_fu_115_ap_idle ),
    .ap_ready( grp_yuv_filter_rgb2yuv_fu_115_ap_ready ),
    .in_channels_ch1_address0( grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_address0 ),
    .in_channels_ch1_ce0( grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_ce0 ),
    .in_channels_ch1_q0( grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_q0 ),
    .in_channels_ch2_address0( grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_address0 ),
    .in_channels_ch2_ce0( grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_ce0 ),
    .in_channels_ch2_q0( grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_q0 ),
    .in_channels_ch3_address0( grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_address0 ),
    .in_channels_ch3_ce0( grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_ce0 ),
    .in_channels_ch3_q0( grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_q0 ),
    .in_width_read( grp_yuv_filter_rgb2yuv_fu_115_in_width_read ),
    .in_height_read( grp_yuv_filter_rgb2yuv_fu_115_in_height_read ),
    .out_channels_ch1_address0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_address0 ),
    .out_channels_ch1_ce0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_ce0 ),
    .out_channels_ch1_we0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_we0 ),
    .out_channels_ch1_d0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_d0 ),
    .out_channels_ch2_address0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_address0 ),
    .out_channels_ch2_ce0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_ce0 ),
    .out_channels_ch2_we0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_we0 ),
    .out_channels_ch2_d0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_d0 ),
    .out_channels_ch3_address0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_address0 ),
    .out_channels_ch3_ce0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_ce0 ),
    .out_channels_ch3_we0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_we0 ),
    .out_channels_ch3_d0( grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_d0 ),
    .ap_return_0( grp_yuv_filter_rgb2yuv_fu_115_ap_return_0 ),
    .ap_return_1( grp_yuv_filter_rgb2yuv_fu_115_ap_return_1 )
);

yuv_filter_yuv2rgb grp_yuv_filter_yuv2rgb_fu_135(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_yuv_filter_yuv2rgb_fu_135_ap_start ),
    .ap_done( grp_yuv_filter_yuv2rgb_fu_135_ap_done ),
    .ap_idle( grp_yuv_filter_yuv2rgb_fu_135_ap_idle ),
    .ap_ready( grp_yuv_filter_yuv2rgb_fu_135_ap_ready ),
    .in_channels_ch1_address0( grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_address0 ),
    .in_channels_ch1_ce0( grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_ce0 ),
    .in_channels_ch1_q0( grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_q0 ),
    .in_channels_ch2_address0( grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_address0 ),
    .in_channels_ch2_ce0( grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_ce0 ),
    .in_channels_ch2_q0( grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_q0 ),
    .in_channels_ch3_address0( grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_address0 ),
    .in_channels_ch3_ce0( grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_ce0 ),
    .in_channels_ch3_q0( grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_q0 ),
    .in_width_read( grp_yuv_filter_yuv2rgb_fu_135_in_width_read ),
    .in_height_read( grp_yuv_filter_yuv2rgb_fu_135_in_height_read ),
    .out_channels_ch1_address0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_address0 ),
    .out_channels_ch1_ce0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_ce0 ),
    .out_channels_ch1_we0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_we0 ),
    .out_channels_ch1_d0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_d0 ),
    .out_channels_ch2_address0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_address0 ),
    .out_channels_ch2_ce0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_ce0 ),
    .out_channels_ch2_we0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_we0 ),
    .out_channels_ch2_d0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_d0 ),
    .out_channels_ch3_address0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_address0 ),
    .out_channels_ch3_ce0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_ce0 ),
    .out_channels_ch3_we0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_we0 ),
    .out_channels_ch3_d0( grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_d0 ),
    .ap_return_0( grp_yuv_filter_yuv2rgb_fu_135_ap_return_0 ),
    .ap_return_1( grp_yuv_filter_yuv2rgb_fu_135_ap_return_1 )
);

yuv_filter_yuv_scale grp_yuv_filter_yuv_scale_fu_150(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_yuv_filter_yuv_scale_fu_150_ap_start ),
    .ap_done( grp_yuv_filter_yuv_scale_fu_150_ap_done ),
    .ap_idle( grp_yuv_filter_yuv_scale_fu_150_ap_idle ),
    .ap_ready( grp_yuv_filter_yuv_scale_fu_150_ap_ready ),
    .in_channels_ch1_address0( grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_address0 ),
    .in_channels_ch1_ce0( grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_ce0 ),
    .in_channels_ch1_q0( grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_q0 ),
    .in_channels_ch2_address0( grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_address0 ),
    .in_channels_ch2_ce0( grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_ce0 ),
    .in_channels_ch2_q0( grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_q0 ),
    .in_channels_ch3_address0( grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_address0 ),
    .in_channels_ch3_ce0( grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_ce0 ),
    .in_channels_ch3_q0( grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_q0 ),
    .in_width_read( grp_yuv_filter_yuv_scale_fu_150_in_width_read ),
    .in_height_read( grp_yuv_filter_yuv_scale_fu_150_in_height_read ),
    .out_channels_ch1_address0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_address0 ),
    .out_channels_ch1_ce0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_ce0 ),
    .out_channels_ch1_we0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_we0 ),
    .out_channels_ch1_d0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_d0 ),
    .out_channels_ch2_address0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_address0 ),
    .out_channels_ch2_ce0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_ce0 ),
    .out_channels_ch2_we0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_we0 ),
    .out_channels_ch2_d0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_d0 ),
    .out_channels_ch3_address0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_address0 ),
    .out_channels_ch3_ce0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_ce0 ),
    .out_channels_ch3_we0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_we0 ),
    .out_channels_ch3_d0( grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_d0 ),
    .Y_scale( grp_yuv_filter_yuv_scale_fu_150_Y_scale ),
    .U_scale( grp_yuv_filter_yuv_scale_fu_150_U_scale ),
    .V_scale( grp_yuv_filter_yuv_scale_fu_150_V_scale ),
    .ap_return_0( grp_yuv_filter_yuv_scale_fu_150_ap_return_0 ),
    .ap_return_1( grp_yuv_filter_yuv_scale_fu_150_ap_return_1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// grp_yuv_filter_rgb2yuv_fu_115_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_yuv_filter_rgb2yuv_fu_115_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_yuv_filter_rgb2yuv_fu_115_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            grp_yuv_filter_rgb2yuv_fu_115_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_yuv_filter_rgb2yuv_fu_115_ap_ready)) begin
            grp_yuv_filter_rgb2yuv_fu_115_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// grp_yuv_filter_yuv2rgb_fu_135_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_yuv_filter_yuv2rgb_fu_135_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_yuv_filter_yuv2rgb_fu_135_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
            grp_yuv_filter_yuv2rgb_fu_135_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_yuv_filter_yuv2rgb_fu_135_ap_ready)) begin
            grp_yuv_filter_yuv2rgb_fu_135_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// grp_yuv_filter_yuv_scale_fu_150_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_yuv_filter_yuv_scale_fu_150_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_yuv_filter_yuv_scale_fu_150_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            grp_yuv_filter_yuv_scale_fu_150_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_yuv_filter_yuv_scale_fu_150_ap_ready)) begin
            grp_yuv_filter_yuv_scale_fu_150_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_logic_0 == grp_yuv_filter_yuv_scale_fu_150_ap_done))) begin
        p_scale_height_reg_234 <= grp_yuv_filter_yuv_scale_fu_150_ap_return_1;
        p_scale_width_reg_229 <= grp_yuv_filter_yuv_scale_fu_150_ap_return_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_logic_0 == grp_yuv_filter_rgb2yuv_fu_115_ap_done))) begin
        p_yuv_height_reg_209 <= grp_yuv_filter_rgb2yuv_fu_115_ap_return_1;
        p_yuv_width_reg_204 <= grp_yuv_filter_rgb2yuv_fu_115_ap_return_0;
    end
end

/// ap_done assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_ap_done or ap_sig_cseq_ST_st6_fsm_5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ap_const_logic_0 == grp_yuv_filter_yuv2rgb_fu_135_ap_done))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_ap_done or ap_sig_cseq_ST_st6_fsm_5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ap_const_logic_0 == grp_yuv_filter_yuv2rgb_fu_135_ap_done))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_22)
begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_91)
begin
    if (ap_sig_bdd_91) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_106)
begin
    if (ap_sig_bdd_106) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_119)
begin
    if (ap_sig_bdd_119) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_285)
begin
    if (ap_sig_bdd_285) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_292)
begin
    if (ap_sig_bdd_292) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// in_channels_ch1_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        in_channels_ch1_ce0 = grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_ce0;
    end else begin
        in_channels_ch1_ce0 = ap_const_logic_0;
    end
end

/// in_channels_ch2_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        in_channels_ch2_ce0 = grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_ce0;
    end else begin
        in_channels_ch2_ce0 = ap_const_logic_0;
    end
end

/// in_channels_ch3_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        in_channels_ch3_ce0 = grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_ce0;
    end else begin
        in_channels_ch3_ce0 = ap_const_logic_0;
    end
end

/// out_channels_ch1_ce0 assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_ce0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        out_channels_ch1_ce0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_ce0;
    end else begin
        out_channels_ch1_ce0 = ap_const_logic_0;
    end
end

/// out_channels_ch1_we0 assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_we0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        out_channels_ch1_we0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_we0;
    end else begin
        out_channels_ch1_we0 = ap_const_logic_0;
    end
end

/// out_channels_ch2_ce0 assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_ce0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        out_channels_ch2_ce0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_ce0;
    end else begin
        out_channels_ch2_ce0 = ap_const_logic_0;
    end
end

/// out_channels_ch2_we0 assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_we0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        out_channels_ch2_we0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_we0;
    end else begin
        out_channels_ch2_we0 = ap_const_logic_0;
    end
end

/// out_channels_ch3_ce0 assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_ce0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        out_channels_ch3_ce0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_ce0;
    end else begin
        out_channels_ch3_ce0 = ap_const_logic_0;
    end
end

/// out_channels_ch3_we0 assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_we0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        out_channels_ch3_we0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_we0;
    end else begin
        out_channels_ch3_we0 = ap_const_logic_0;
    end
end

/// out_height_ap_vld assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_ap_done or ap_sig_cseq_ST_st6_fsm_5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ap_const_logic_0 == grp_yuv_filter_yuv2rgb_fu_135_ap_done))) begin
        out_height_ap_vld = ap_const_logic_1;
    end else begin
        out_height_ap_vld = ap_const_logic_0;
    end
end

/// out_width_ap_vld assign process. ///
always @ (grp_yuv_filter_yuv2rgb_fu_135_ap_done or ap_sig_cseq_ST_st6_fsm_5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ap_const_logic_0 == grp_yuv_filter_yuv2rgb_fu_135_ap_done))) begin
        out_width_ap_vld = ap_const_logic_1;
    end else begin
        out_width_ap_vld = ap_const_logic_0;
    end
end

/// p_scale_channels_ch1_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_address0 or grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_address0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_scale_channels_ch1_address0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        p_scale_channels_ch1_address0 = grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_address0;
    end else begin
        p_scale_channels_ch1_address0 = 'bx;
    end
end

/// p_scale_channels_ch1_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_ce0 or grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_ce0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_scale_channels_ch1_ce0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        p_scale_channels_ch1_ce0 = grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_ce0;
    end else begin
        p_scale_channels_ch1_ce0 = ap_const_logic_0;
    end
end

/// p_scale_channels_ch1_we0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_we0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_scale_channels_ch1_we0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_we0;
    end else begin
        p_scale_channels_ch1_we0 = ap_const_logic_0;
    end
end

/// p_scale_channels_ch2_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_address0 or grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_address0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_scale_channels_ch2_address0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        p_scale_channels_ch2_address0 = grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_address0;
    end else begin
        p_scale_channels_ch2_address0 = 'bx;
    end
end

/// p_scale_channels_ch2_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_ce0 or grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_ce0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_scale_channels_ch2_ce0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        p_scale_channels_ch2_ce0 = grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_ce0;
    end else begin
        p_scale_channels_ch2_ce0 = ap_const_logic_0;
    end
end

/// p_scale_channels_ch2_we0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_we0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_scale_channels_ch2_we0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_we0;
    end else begin
        p_scale_channels_ch2_we0 = ap_const_logic_0;
    end
end

/// p_scale_channels_ch3_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_address0 or grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_address0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_scale_channels_ch3_address0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        p_scale_channels_ch3_address0 = grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_address0;
    end else begin
        p_scale_channels_ch3_address0 = 'bx;
    end
end

/// p_scale_channels_ch3_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_ce0 or grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_ce0 or ap_sig_cseq_ST_st6_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_scale_channels_ch3_ce0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        p_scale_channels_ch3_ce0 = grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_ce0;
    end else begin
        p_scale_channels_ch3_ce0 = ap_const_logic_0;
    end
end

/// p_scale_channels_ch3_we0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_we0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_scale_channels_ch3_we0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_we0;
    end else begin
        p_scale_channels_ch3_we0 = ap_const_logic_0;
    end
end

/// p_yuv_channels_ch1_address0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_address0 or grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_address0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_yuv_channels_ch1_address0 = grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_yuv_channels_ch1_address0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_address0;
    end else begin
        p_yuv_channels_ch1_address0 = 'bx;
    end
end

/// p_yuv_channels_ch1_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_ce0 or grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_yuv_channels_ch1_ce0 = grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_yuv_channels_ch1_ce0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_ce0;
    end else begin
        p_yuv_channels_ch1_ce0 = ap_const_logic_0;
    end
end

/// p_yuv_channels_ch1_we0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_we0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_yuv_channels_ch1_we0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_we0;
    end else begin
        p_yuv_channels_ch1_we0 = ap_const_logic_0;
    end
end

/// p_yuv_channels_ch2_address0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_address0 or grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_address0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_yuv_channels_ch2_address0 = grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_yuv_channels_ch2_address0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_address0;
    end else begin
        p_yuv_channels_ch2_address0 = 'bx;
    end
end

/// p_yuv_channels_ch2_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_ce0 or grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_yuv_channels_ch2_ce0 = grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_yuv_channels_ch2_ce0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_ce0;
    end else begin
        p_yuv_channels_ch2_ce0 = ap_const_logic_0;
    end
end

/// p_yuv_channels_ch2_we0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_we0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_yuv_channels_ch2_we0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_we0;
    end else begin
        p_yuv_channels_ch2_we0 = ap_const_logic_0;
    end
end

/// p_yuv_channels_ch3_address0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_address0 or grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_address0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_yuv_channels_ch3_address0 = grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_yuv_channels_ch3_address0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_address0;
    end else begin
        p_yuv_channels_ch3_address0 = 'bx;
    end
end

/// p_yuv_channels_ch3_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_ce0 or grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        p_yuv_channels_ch3_ce0 = grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_yuv_channels_ch3_ce0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_ce0;
    end else begin
        p_yuv_channels_ch3_ce0 = ap_const_logic_0;
    end
end

/// p_yuv_channels_ch3_we0 assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_we0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        p_yuv_channels_ch3_we0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_we0;
    end else begin
        p_yuv_channels_ch3_we0 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or grp_yuv_filter_rgb2yuv_fu_115_ap_done or grp_yuv_filter_yuv_scale_fu_150_ap_done or grp_yuv_filter_yuv2rgb_fu_135_ap_done)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(ap_const_logic_0 == grp_yuv_filter_rgb2yuv_fu_115_ap_done)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(ap_const_logic_0 == grp_yuv_filter_yuv_scale_fu_150_ap_done)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            if (~(ap_const_logic_0 == grp_yuv_filter_yuv2rgb_fu_135_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_sig_bdd_106 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_106 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_119 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_119 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_22 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_285 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_285 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_292 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_292 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_91 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_91 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end
assign grp_yuv_filter_rgb2yuv_fu_115_ap_start = grp_yuv_filter_rgb2yuv_fu_115_ap_start_ap_start_reg;
assign grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_q0 = in_channels_ch1_q0;
assign grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_q0 = in_channels_ch2_q0;
assign grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_q0 = in_channels_ch3_q0;
assign grp_yuv_filter_rgb2yuv_fu_115_in_height_read = in_height;
assign grp_yuv_filter_rgb2yuv_fu_115_in_width_read = in_width;
assign grp_yuv_filter_yuv2rgb_fu_135_ap_start = grp_yuv_filter_yuv2rgb_fu_135_ap_start_ap_start_reg;
assign grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch1_q0 = p_scale_channels_ch1_q0;
assign grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch2_q0 = p_scale_channels_ch2_q0;
assign grp_yuv_filter_yuv2rgb_fu_135_in_channels_ch3_q0 = p_scale_channels_ch3_q0;
assign grp_yuv_filter_yuv2rgb_fu_135_in_height_read = p_scale_height_reg_234;
assign grp_yuv_filter_yuv2rgb_fu_135_in_width_read = p_scale_width_reg_229;
assign grp_yuv_filter_yuv_scale_fu_150_U_scale = U_scale;
assign grp_yuv_filter_yuv_scale_fu_150_V_scale = V_scale;
assign grp_yuv_filter_yuv_scale_fu_150_Y_scale = Y_scale;
assign grp_yuv_filter_yuv_scale_fu_150_ap_start = grp_yuv_filter_yuv_scale_fu_150_ap_start_ap_start_reg;
assign grp_yuv_filter_yuv_scale_fu_150_in_channels_ch1_q0 = p_yuv_channels_ch1_q0;
assign grp_yuv_filter_yuv_scale_fu_150_in_channels_ch2_q0 = p_yuv_channels_ch2_q0;
assign grp_yuv_filter_yuv_scale_fu_150_in_channels_ch3_q0 = p_yuv_channels_ch3_q0;
assign grp_yuv_filter_yuv_scale_fu_150_in_height_read = p_yuv_height_reg_209;
assign grp_yuv_filter_yuv_scale_fu_150_in_width_read = p_yuv_width_reg_204;
assign in_channels_ch1_address0 = grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch1_address0;
assign in_channels_ch2_address0 = grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch2_address0;
assign in_channels_ch3_address0 = grp_yuv_filter_rgb2yuv_fu_115_in_channels_ch3_address0;
assign out_channels_ch1_address0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_address0;
assign out_channels_ch1_d0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch1_d0;
assign out_channels_ch2_address0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_address0;
assign out_channels_ch2_d0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch2_d0;
assign out_channels_ch3_address0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_address0;
assign out_channels_ch3_d0 = grp_yuv_filter_yuv2rgb_fu_135_out_channels_ch3_d0;
assign out_height = grp_yuv_filter_yuv2rgb_fu_135_ap_return_1;
assign out_width = grp_yuv_filter_yuv2rgb_fu_135_ap_return_0;
assign p_scale_channels_ch1_d0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch1_d0;
assign p_scale_channels_ch2_d0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch2_d0;
assign p_scale_channels_ch3_d0 = grp_yuv_filter_yuv_scale_fu_150_out_channels_ch3_d0;
assign p_yuv_channels_ch1_d0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch1_d0;
assign p_yuv_channels_ch2_d0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch2_d0;
assign p_yuv_channels_ch3_d0 = grp_yuv_filter_rgb2yuv_fu_115_out_channels_ch3_d0;


endmodule //yuv_filter

