// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmotorctrl.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMotorctrl_CfgInitialize(XMotorctrl *InstancePtr, XMotorctrl_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv0_BaseAddress = ConfigPtr->Slv0_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMotorctrl_SetPwmr(XMotorctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMotorctrl_WriteReg(InstancePtr->Slv0_BaseAddress, XMOTORCTRL_SLV0_ADDR_PWMR_DATA, Data);
}

u32 XMotorctrl_GetPwmr(XMotorctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMotorctrl_ReadReg(InstancePtr->Slv0_BaseAddress, XMOTORCTRL_SLV0_ADDR_PWMR_DATA);
    return Data;
}

void XMotorctrl_SetPwml(XMotorctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMotorctrl_WriteReg(InstancePtr->Slv0_BaseAddress, XMOTORCTRL_SLV0_ADDR_PWML_DATA, Data);
}

u32 XMotorctrl_GetPwml(XMotorctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMotorctrl_ReadReg(InstancePtr->Slv0_BaseAddress, XMOTORCTRL_SLV0_ADDR_PWML_DATA);
    return Data;
}

void XMotorctrl_SetDirection(XMotorctrl *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMotorctrl_WriteReg(InstancePtr->Slv0_BaseAddress, XMOTORCTRL_SLV0_ADDR_DIRECTION_DATA, Data);
}

u32 XMotorctrl_GetDirection(XMotorctrl *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMotorctrl_ReadReg(InstancePtr->Slv0_BaseAddress, XMOTORCTRL_SLV0_ADDR_DIRECTION_DATA);
    return Data;
}

