webtalk_init -webtalk_dir C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\AI_Project\\ZyboCar\\ZyboCar.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "fr maj 29 17:58:16 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211042119_0_0_461" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dls5pkjnukh2803bavrq99c7du" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_30" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU       Q 820  @ 1.73GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1729 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1432913567488" -context "sdk\\\\application/1432913567488"
webtalk_add_data -client sdk -key hwid -value "1432224082633" -context "sdk\\\\application/1432913567488"
webtalk_add_data -client sdk -key bspid -value "1432224094821" -context "sdk\\\\application/1432913567488"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1432913567488"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1432913567488"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1432913567488"
webtalk_transmit -clientid 984078892 -regid "211042119_0_0_461" -xml C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\AI_Project\\ZyboCar\\ZyboCar.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\AI_Project\\ZyboCar\\ZyboCar.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Kasper\\Documents\\GitHub\\TIHSC\\AI_Project\\ZyboCar\\ZyboCar.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
