// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "yuv_filter_yuv2rgb.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic yuv_filter_yuv2rgb::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic yuv_filter_yuv2rgb::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> yuv_filter_yuv2rgb::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> yuv_filter_yuv2rgb::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<3> yuv_filter_yuv2rgb::ap_ST_st9_fsm_2 = "100";
const bool yuv_filter_yuv2rgb::ap_true = true;
const sc_lv<32> yuv_filter_yuv2rgb::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> yuv_filter_yuv2rgb::ap_const_lv1_1 = "1";
const sc_lv<32> yuv_filter_yuv2rgb::ap_const_lv32_1 = "1";
const sc_lv<1> yuv_filter_yuv2rgb::ap_const_lv1_0 = "0";
const sc_lv<16> yuv_filter_yuv2rgb::ap_const_lv16_0 = "0000000000000000";
const sc_lv<16> yuv_filter_yuv2rgb::ap_const_lv16_1 = "1";
const sc_lv<10> yuv_filter_yuv2rgb::ap_const_lv10_0 = "0000000000";
const sc_lv<8> yuv_filter_yuv2rgb::ap_const_lv8_0 = "00000000";
const sc_lv<9> yuv_filter_yuv2rgb::ap_const_lv9_1F0 = "111110000";
const sc_lv<8> yuv_filter_yuv2rgb::ap_const_lv8_80 = "10000000";
const sc_lv<18> yuv_filter_yuv2rgb::ap_const_lv18_12A = "100101010";
const sc_lv<18> yuv_filter_yuv2rgb::ap_const_lv18_80 = "10000000";
const sc_lv<18> yuv_filter_yuv2rgb::ap_const_lv18_199 = "110011001";
const sc_lv<32> yuv_filter_yuv2rgb::ap_const_lv32_10 = "10000";
const sc_lv<32> yuv_filter_yuv2rgb::ap_const_lv32_11 = "10001";
const sc_lv<32> yuv_filter_yuv2rgb::ap_const_lv32_8 = "1000";
const sc_lv<32> yuv_filter_yuv2rgb::ap_const_lv32_F = "1111";
const sc_lv<17> yuv_filter_yuv2rgb::ap_const_lv17_1FF30 = "11111111100110000";
const sc_lv<9> yuv_filter_yuv2rgb::ap_const_lv9_0 = "000000000";
const sc_lv<2> yuv_filter_yuv2rgb::ap_const_lv2_0 = "00";
const sc_lv<32> yuv_filter_yuv2rgb::ap_const_lv32_12 = "10010";
const sc_lv<2> yuv_filter_yuv2rgb::ap_const_lv2_1 = "1";
const sc_lv<8> yuv_filter_yuv2rgb::ap_const_lv8_FF = "11111111";
const sc_lv<16> yuv_filter_yuv2rgb::ap_const_lv16_FF9C = "1111111110011100";
const sc_lv<3> yuv_filter_yuv2rgb::ap_const_lv3_0 = "000";
const sc_lv<32> yuv_filter_yuv2rgb::ap_const_lv32_2 = "10";

yuv_filter_yuv2rgb::yuv_filter_yuv2rgb(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_C_fu_331_p2);
    sensitive << ( tmp_40_cast_fu_328_p1 );

    SC_METHOD(thread_D_fu_337_p2);
    sensitive << ( in_channels_ch2_q0 );

    SC_METHOD(thread_E_fu_343_p2);
    sensitive << ( in_channels_ch3_q0 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( in_width_read );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( in_height_read );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_2 );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_392);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_92);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_bdd_92 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_2);
    sensitive << ( ap_sig_bdd_392 );

    SC_METHOD(thread_bound_fu_236_p0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( bound_fu_236_p00 );

    SC_METHOD(thread_bound_fu_236_p00);
    sensitive << ( in_width_read );

    SC_METHOD(thread_bound_fu_236_p1);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( bound_fu_236_p10 );

    SC_METHOD(thread_bound_fu_236_p10);
    sensitive << ( in_height_read );

    SC_METHOD(thread_bound_fu_236_p2);
    sensitive << ( bound_fu_236_p0 );
    sensitive << ( bound_fu_236_p1 );

    SC_METHOD(thread_exitcond_flatten_fu_242_p2);
    sensitive << ( indvar_flatten_reg_194 );
    sensitive << ( bound_reg_635 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_fu_253_p2);
    sensitive << ( in_height_read );
    sensitive << ( y_reg_216 );
    sensitive << ( exitcond_flatten_fu_242_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_icmp1_fu_588_p2);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it5 );
    sensitive << ( tmp_4_reg_750 );

    SC_METHOD(thread_icmp2_fu_562_p2);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4 );
    sensitive << ( tmp_8_reg_735 );

    SC_METHOD(thread_icmp_fu_490_p2);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4 );
    sensitive << ( tmp_1_reg_715 );

    SC_METHOD(thread_in_channels_ch1_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_10_fu_323_p1 );

    SC_METHOD(thread_in_channels_ch1_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_in_channels_ch2_address0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_10_reg_666 );

    SC_METHOD(thread_in_channels_ch2_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_in_channels_ch3_address0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_10_reg_666 );

    SC_METHOD(thread_in_channels_ch3_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_indvar_flatten_next_fu_247_p2);
    sensitive << ( indvar_flatten_reg_194 );

    SC_METHOD(thread_out_channels_ch1_address0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_tmp_10_reg_666_pp0_it4 );

    SC_METHOD(thread_out_channels_ch1_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_out_channels_ch1_d0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( phitmp_reg_725 );
    sensitive << ( tmp_3_fu_503_p2 );
    sensitive << ( p_phitmp_fu_495_p3 );

    SC_METHOD(thread_out_channels_ch1_we0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4 );

    SC_METHOD(thread_out_channels_ch2_address0);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_tmp_10_reg_666_pp0_it5 );

    SC_METHOD(thread_out_channels_ch2_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it6 );

    SC_METHOD(thread_out_channels_ch2_d0);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( phitmp2_reg_760 );
    sensitive << ( tmp_6_fu_601_p2 );
    sensitive << ( p_phitmp2_fu_593_p3 );

    SC_METHOD(thread_out_channels_ch2_we0);
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it5 );

    SC_METHOD(thread_out_channels_ch3_address0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_tmp_10_reg_666_pp0_it4 );

    SC_METHOD(thread_out_channels_ch3_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_out_channels_ch3_d0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( phitmp3_reg_745 );
    sensitive << ( tmp_9_fu_575_p2 );
    sensitive << ( p_phitmp3_fu_567_p3 );

    SC_METHOD(thread_out_channels_ch3_we0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4 );

    SC_METHOD(thread_p_addr1_fu_317_p2);
    sensitive << ( p_addr_fu_311_p2 );
    sensitive << ( tmp_trn_cast_fu_286_p1 );

    SC_METHOD(thread_p_addr_fu_311_p2);
    sensitive << ( p_shl9_cast_fu_296_p1 );
    sensitive << ( p_shl10_cast_fu_307_p1 );

    SC_METHOD(thread_p_phitmp2_fu_593_p3);
    sensitive << ( icmp1_fu_588_p2 );

    SC_METHOD(thread_p_phitmp3_fu_567_p3);
    sensitive << ( icmp2_fu_562_p2 );

    SC_METHOD(thread_p_phitmp_fu_495_p3);
    sensitive << ( icmp_fu_490_p2 );

    SC_METHOD(thread_p_shl10_cast_fu_307_p1);
    sensitive << ( tmp_7_fu_300_p3 );

    SC_METHOD(thread_p_shl1_cast_fu_443_p1);
    sensitive << ( p_shl1_fu_436_p3 );

    SC_METHOD(thread_p_shl1_fu_436_p3);
    sensitive << ( D_reg_695 );

    SC_METHOD(thread_p_shl9_cast_fu_296_p1);
    sensitive << ( tmp_fu_289_p3 );

    SC_METHOD(thread_p_shl_cast_fu_432_p1);
    sensitive << ( p_shl_fu_425_p3 );

    SC_METHOD(thread_p_shl_fu_425_p3);
    sensitive << ( D_reg_695 );

    SC_METHOD(thread_tmp1_fu_420_p2);
    sensitive << ( tmp_24_reg_708 );
    sensitive << ( tmp_29_cast_fu_416_p1 );

    SC_METHOD(thread_tmp2_cast_fu_452_p1);
    sensitive << ( tmp2_fu_447_p2 );

    SC_METHOD(thread_tmp2_fu_447_p2);
    sensitive << ( tmp_24_reg_708 );
    sensitive << ( p_shl1_cast_fu_443_p1 );

    SC_METHOD(thread_tmp_10_fu_323_p1);
    sensitive << ( p_addr1_fu_317_p2 );

    SC_METHOD(thread_tmp_22_fu_353_p0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( C_fu_331_p2 );

    SC_METHOD(thread_tmp_22_fu_353_p2);
    sensitive << ( tmp_22_fu_353_p0 );

    SC_METHOD(thread_tmp_23_fu_371_p0);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( E_reg_702 );

    SC_METHOD(thread_tmp_23_fu_371_p2);
    sensitive << ( tmp_23_fu_371_p0 );

    SC_METHOD(thread_tmp_24_fu_359_p2);
    sensitive << ( tmp_22_fu_353_p2 );

    SC_METHOD(thread_tmp_25_fu_377_p2);
    sensitive << ( tmp_24_reg_708 );
    sensitive << ( tmp_23_fu_371_p2 );

    SC_METHOD(thread_tmp_26_fu_519_p0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppstg_D_reg_695_pp0_it4 );

    SC_METHOD(thread_tmp_26_fu_519_p2);
    sensitive << ( tmp_26_fu_519_p0 );

    SC_METHOD(thread_tmp_27_fu_410_p0);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( E_reg_702 );

    SC_METHOD(thread_tmp_27_fu_410_p2);
    sensitive << ( tmp_27_fu_410_p0 );

    SC_METHOD(thread_tmp_28_cast_fu_525_p1);
    sensitive << ( tmp_26_fu_519_p2 );

    SC_METHOD(thread_tmp_28_fu_529_p2);
    sensitive << ( tmp1_reg_730 );
    sensitive << ( tmp_28_cast_fu_525_p1 );

    SC_METHOD(thread_tmp_29_cast_fu_416_p1);
    sensitive << ( tmp_27_fu_410_p2 );

    SC_METHOD(thread_tmp_29_fu_456_p2);
    sensitive << ( tmp2_cast_fu_452_p1 );
    sensitive << ( p_shl_cast_fu_432_p1 );

    SC_METHOD(thread_tmp_3_fu_503_p2);
    sensitive << ( tmp_2_reg_720 );
    sensitive << ( icmp_fu_490_p2 );

    SC_METHOD(thread_tmp_40_cast_fu_328_p1);
    sensitive << ( Y_reg_680 );

    SC_METHOD(thread_tmp_6_fu_601_p2);
    sensitive << ( tmp_5_reg_755 );
    sensitive << ( icmp1_fu_588_p2 );

    SC_METHOD(thread_tmp_7_fu_300_p3);
    sensitive << ( x_mid2_reg_654 );

    SC_METHOD(thread_tmp_9_fu_575_p2);
    sensitive << ( tmp_11_reg_740 );
    sensitive << ( icmp2_fu_562_p2 );

    SC_METHOD(thread_tmp_fu_289_p3);
    sensitive << ( x_mid2_reg_654 );

    SC_METHOD(thread_tmp_trn_cast_fu_286_p1);
    sensitive << ( y_mid2_reg_649 );

    SC_METHOD(thread_x_mid2_fu_272_p3);
    sensitive << ( x_phi_fu_209_p4 );
    sensitive << ( exitcond_fu_253_p2 );
    sensitive << ( x_s_fu_266_p2 );

    SC_METHOD(thread_x_phi_fu_209_p4);
    sensitive << ( x_reg_205 );
    sensitive << ( exitcond_flatten_reg_640 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( x_mid2_reg_654 );

    SC_METHOD(thread_x_s_fu_266_p2);
    sensitive << ( x_phi_fu_209_p4 );

    SC_METHOD(thread_y_3_fu_280_p2);
    sensitive << ( y_mid2_fu_258_p3 );

    SC_METHOD(thread_y_mid2_fu_258_p3);
    sensitive << ( y_reg_216 );
    sensitive << ( exitcond_fu_253_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten_fu_242_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );

    ap_CS_fsm = "001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "yuv_filter_yuv2rgb_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_channels_ch1_address0, "(port)in_channels_ch1_address0");
    sc_trace(mVcdFile, in_channels_ch1_ce0, "(port)in_channels_ch1_ce0");
    sc_trace(mVcdFile, in_channels_ch1_q0, "(port)in_channels_ch1_q0");
    sc_trace(mVcdFile, in_channels_ch2_address0, "(port)in_channels_ch2_address0");
    sc_trace(mVcdFile, in_channels_ch2_ce0, "(port)in_channels_ch2_ce0");
    sc_trace(mVcdFile, in_channels_ch2_q0, "(port)in_channels_ch2_q0");
    sc_trace(mVcdFile, in_channels_ch3_address0, "(port)in_channels_ch3_address0");
    sc_trace(mVcdFile, in_channels_ch3_ce0, "(port)in_channels_ch3_ce0");
    sc_trace(mVcdFile, in_channels_ch3_q0, "(port)in_channels_ch3_q0");
    sc_trace(mVcdFile, in_width_read, "(port)in_width_read");
    sc_trace(mVcdFile, in_height_read, "(port)in_height_read");
    sc_trace(mVcdFile, out_channels_ch1_address0, "(port)out_channels_ch1_address0");
    sc_trace(mVcdFile, out_channels_ch1_ce0, "(port)out_channels_ch1_ce0");
    sc_trace(mVcdFile, out_channels_ch1_we0, "(port)out_channels_ch1_we0");
    sc_trace(mVcdFile, out_channels_ch1_d0, "(port)out_channels_ch1_d0");
    sc_trace(mVcdFile, out_channels_ch2_address0, "(port)out_channels_ch2_address0");
    sc_trace(mVcdFile, out_channels_ch2_ce0, "(port)out_channels_ch2_ce0");
    sc_trace(mVcdFile, out_channels_ch2_we0, "(port)out_channels_ch2_we0");
    sc_trace(mVcdFile, out_channels_ch2_d0, "(port)out_channels_ch2_d0");
    sc_trace(mVcdFile, out_channels_ch3_address0, "(port)out_channels_ch3_address0");
    sc_trace(mVcdFile, out_channels_ch3_ce0, "(port)out_channels_ch3_ce0");
    sc_trace(mVcdFile, out_channels_ch3_we0, "(port)out_channels_ch3_we0");
    sc_trace(mVcdFile, out_channels_ch3_d0, "(port)out_channels_ch3_d0");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, indvar_flatten_reg_194, "indvar_flatten_reg_194");
    sc_trace(mVcdFile, x_reg_205, "x_reg_205");
    sc_trace(mVcdFile, y_reg_216, "y_reg_216");
    sc_trace(mVcdFile, bound_fu_236_p2, "bound_fu_236_p2");
    sc_trace(mVcdFile, bound_reg_635, "bound_reg_635");
    sc_trace(mVcdFile, exitcond_flatten_fu_242_p2, "exitcond_flatten_fu_242_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_640, "exitcond_flatten_reg_640");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_92, "ap_sig_bdd_92");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it1, "ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it2, "ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it3, "ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4, "ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it5, "ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it5");
    sc_trace(mVcdFile, indvar_flatten_next_fu_247_p2, "indvar_flatten_next_fu_247_p2");
    sc_trace(mVcdFile, y_mid2_fu_258_p3, "y_mid2_fu_258_p3");
    sc_trace(mVcdFile, y_mid2_reg_649, "y_mid2_reg_649");
    sc_trace(mVcdFile, x_mid2_fu_272_p3, "x_mid2_fu_272_p3");
    sc_trace(mVcdFile, x_mid2_reg_654, "x_mid2_reg_654");
    sc_trace(mVcdFile, y_3_fu_280_p2, "y_3_fu_280_p2");
    sc_trace(mVcdFile, tmp_10_fu_323_p1, "tmp_10_fu_323_p1");
    sc_trace(mVcdFile, tmp_10_reg_666, "tmp_10_reg_666");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_10_reg_666_pp0_it2, "ap_reg_ppstg_tmp_10_reg_666_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_10_reg_666_pp0_it3, "ap_reg_ppstg_tmp_10_reg_666_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_10_reg_666_pp0_it4, "ap_reg_ppstg_tmp_10_reg_666_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_10_reg_666_pp0_it5, "ap_reg_ppstg_tmp_10_reg_666_pp0_it5");
    sc_trace(mVcdFile, Y_reg_680, "Y_reg_680");
    sc_trace(mVcdFile, D_fu_337_p2, "D_fu_337_p2");
    sc_trace(mVcdFile, D_reg_695, "D_reg_695");
    sc_trace(mVcdFile, ap_reg_ppstg_D_reg_695_pp0_it4, "ap_reg_ppstg_D_reg_695_pp0_it4");
    sc_trace(mVcdFile, E_fu_343_p2, "E_fu_343_p2");
    sc_trace(mVcdFile, E_reg_702, "E_reg_702");
    sc_trace(mVcdFile, tmp_24_fu_359_p2, "tmp_24_fu_359_p2");
    sc_trace(mVcdFile, tmp_24_reg_708, "tmp_24_reg_708");
    sc_trace(mVcdFile, tmp_1_reg_715, "tmp_1_reg_715");
    sc_trace(mVcdFile, tmp_2_reg_720, "tmp_2_reg_720");
    sc_trace(mVcdFile, phitmp_reg_725, "phitmp_reg_725");
    sc_trace(mVcdFile, tmp1_fu_420_p2, "tmp1_fu_420_p2");
    sc_trace(mVcdFile, tmp1_reg_730, "tmp1_reg_730");
    sc_trace(mVcdFile, tmp_8_reg_735, "tmp_8_reg_735");
    sc_trace(mVcdFile, tmp_11_reg_740, "tmp_11_reg_740");
    sc_trace(mVcdFile, phitmp3_reg_745, "phitmp3_reg_745");
    sc_trace(mVcdFile, tmp_4_reg_750, "tmp_4_reg_750");
    sc_trace(mVcdFile, tmp_5_reg_755, "tmp_5_reg_755");
    sc_trace(mVcdFile, phitmp2_reg_760, "phitmp2_reg_760");
    sc_trace(mVcdFile, x_phi_fu_209_p4, "x_phi_fu_209_p4");
    sc_trace(mVcdFile, bound_fu_236_p0, "bound_fu_236_p0");
    sc_trace(mVcdFile, bound_fu_236_p1, "bound_fu_236_p1");
    sc_trace(mVcdFile, exitcond_fu_253_p2, "exitcond_fu_253_p2");
    sc_trace(mVcdFile, x_s_fu_266_p2, "x_s_fu_266_p2");
    sc_trace(mVcdFile, tmp_fu_289_p3, "tmp_fu_289_p3");
    sc_trace(mVcdFile, tmp_7_fu_300_p3, "tmp_7_fu_300_p3");
    sc_trace(mVcdFile, p_shl9_cast_fu_296_p1, "p_shl9_cast_fu_296_p1");
    sc_trace(mVcdFile, p_shl10_cast_fu_307_p1, "p_shl10_cast_fu_307_p1");
    sc_trace(mVcdFile, p_addr_fu_311_p2, "p_addr_fu_311_p2");
    sc_trace(mVcdFile, tmp_trn_cast_fu_286_p1, "tmp_trn_cast_fu_286_p1");
    sc_trace(mVcdFile, p_addr1_fu_317_p2, "p_addr1_fu_317_p2");
    sc_trace(mVcdFile, tmp_40_cast_fu_328_p1, "tmp_40_cast_fu_328_p1");
    sc_trace(mVcdFile, C_fu_331_p2, "C_fu_331_p2");
    sc_trace(mVcdFile, tmp_22_fu_353_p0, "tmp_22_fu_353_p0");
    sc_trace(mVcdFile, tmp_22_fu_353_p2, "tmp_22_fu_353_p2");
    sc_trace(mVcdFile, tmp_23_fu_371_p0, "tmp_23_fu_371_p0");
    sc_trace(mVcdFile, tmp_23_fu_371_p2, "tmp_23_fu_371_p2");
    sc_trace(mVcdFile, tmp_25_fu_377_p2, "tmp_25_fu_377_p2");
    sc_trace(mVcdFile, tmp_27_fu_410_p0, "tmp_27_fu_410_p0");
    sc_trace(mVcdFile, tmp_27_fu_410_p2, "tmp_27_fu_410_p2");
    sc_trace(mVcdFile, tmp_29_cast_fu_416_p1, "tmp_29_cast_fu_416_p1");
    sc_trace(mVcdFile, p_shl_fu_425_p3, "p_shl_fu_425_p3");
    sc_trace(mVcdFile, p_shl1_fu_436_p3, "p_shl1_fu_436_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_443_p1, "p_shl1_cast_fu_443_p1");
    sc_trace(mVcdFile, tmp2_fu_447_p2, "tmp2_fu_447_p2");
    sc_trace(mVcdFile, tmp2_cast_fu_452_p1, "tmp2_cast_fu_452_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_432_p1, "p_shl_cast_fu_432_p1");
    sc_trace(mVcdFile, tmp_29_fu_456_p2, "tmp_29_fu_456_p2");
    sc_trace(mVcdFile, icmp_fu_490_p2, "icmp_fu_490_p2");
    sc_trace(mVcdFile, tmp_3_fu_503_p2, "tmp_3_fu_503_p2");
    sc_trace(mVcdFile, p_phitmp_fu_495_p3, "p_phitmp_fu_495_p3");
    sc_trace(mVcdFile, tmp_26_fu_519_p0, "tmp_26_fu_519_p0");
    sc_trace(mVcdFile, tmp_26_fu_519_p2, "tmp_26_fu_519_p2");
    sc_trace(mVcdFile, tmp_28_cast_fu_525_p1, "tmp_28_cast_fu_525_p1");
    sc_trace(mVcdFile, tmp_28_fu_529_p2, "tmp_28_fu_529_p2");
    sc_trace(mVcdFile, icmp2_fu_562_p2, "icmp2_fu_562_p2");
    sc_trace(mVcdFile, tmp_9_fu_575_p2, "tmp_9_fu_575_p2");
    sc_trace(mVcdFile, p_phitmp3_fu_567_p3, "p_phitmp3_fu_567_p3");
    sc_trace(mVcdFile, icmp1_fu_588_p2, "icmp1_fu_588_p2");
    sc_trace(mVcdFile, tmp_6_fu_601_p2, "tmp_6_fu_601_p2");
    sc_trace(mVcdFile, p_phitmp2_fu_593_p3, "p_phitmp2_fu_593_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_2, "ap_sig_cseq_ST_st9_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_392, "ap_sig_bdd_392");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, bound_fu_236_p00, "bound_fu_236_p00");
    sc_trace(mVcdFile, bound_fu_236_p10, "bound_fu_236_p10");
#endif

    }
}

yuv_filter_yuv2rgb::~yuv_filter_yuv2rgb() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void yuv_filter_yuv2rgb::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond_flatten_fu_242_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             esl_seteq<1,1,1>(exitcond_flatten_fu_242_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                     !esl_seteq<1,1,1>(exitcond_flatten_fu_242_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_242_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_194 = indvar_flatten_next_fu_247_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten_reg_194 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_640.read(), ap_const_lv1_0))) {
        x_reg_205 = x_mid2_reg_654.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        x_reg_205 = ap_const_lv16_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_242_p2.read(), ap_const_lv1_0))) {
        y_reg_216 = y_3_fu_280_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        y_reg_216 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it2.read(), ap_const_lv1_0)) {
        D_reg_695 = D_fu_337_p2.read();
        E_reg_702 = E_fu_343_p2.read();
        tmp_24_reg_708 = tmp_24_fu_359_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it1.read(), ap_const_lv1_0)) {
        Y_reg_680 = in_channels_ch1_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_true, ap_true)) {
        ap_reg_ppstg_D_reg_695_pp0_it4 = D_reg_695.read();
        ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it2 = ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it1.read();
        ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it3 = ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it2.read();
        ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4 = ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it3.read();
        ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it5 = ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4.read();
        ap_reg_ppstg_tmp_10_reg_666_pp0_it2 = tmp_10_reg_666.read();
        ap_reg_ppstg_tmp_10_reg_666_pp0_it3 = ap_reg_ppstg_tmp_10_reg_666_pp0_it2.read();
        ap_reg_ppstg_tmp_10_reg_666_pp0_it4 = ap_reg_ppstg_tmp_10_reg_666_pp0_it3.read();
        ap_reg_ppstg_tmp_10_reg_666_pp0_it5 = ap_reg_ppstg_tmp_10_reg_666_pp0_it4.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it1 = exitcond_flatten_reg_640.read();
        exitcond_flatten_reg_640 = exitcond_flatten_fu_242_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        bound_reg_635 = bound_fu_236_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4.read(), ap_const_lv1_0)) {
        phitmp2_reg_760 = tmp_28_fu_529_p2.read().range(15, 8);
        tmp_4_reg_750 = tmp_28_fu_529_p2.read().range(17, 16);
        tmp_5_reg_755 = tmp_28_fu_529_p2.read().range(17, 17);
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it3.read(), ap_const_lv1_0)) {
        phitmp3_reg_745 = tmp_29_fu_456_p2.read().range(15, 8);
        phitmp_reg_725 = tmp_25_fu_377_p2.read().range(15, 8);
        tmp1_reg_730 = tmp1_fu_420_p2.read();
        tmp_11_reg_740 = tmp_29_fu_456_p2.read().range(18, 18);
        tmp_1_reg_715 = tmp_25_fu_377_p2.read().range(17, 16);
        tmp_2_reg_720 = tmp_25_fu_377_p2.read().range(17, 17);
        tmp_8_reg_735 = tmp_29_fu_456_p2.read().range(18, 16);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_640.read(), ap_const_lv1_0))) {
        tmp_10_reg_666 = tmp_10_fu_323_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_242_p2.read(), ap_const_lv1_0))) {
        x_mid2_reg_654 = x_mid2_fu_272_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_242_p2.read(), ap_const_lv1_0))) {
        y_mid2_reg_649 = y_mid2_fu_258_p3.read();
    }
}

void yuv_filter_yuv2rgb::thread_C_fu_331_p2() {
    C_fu_331_p2 = (!tmp_40_cast_fu_328_p1.read().is_01() || !ap_const_lv9_1F0.is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_40_cast_fu_328_p1.read()) + sc_bigint<9>(ap_const_lv9_1F0));
}

void yuv_filter_yuv2rgb::thread_D_fu_337_p2() {
    D_fu_337_p2 = (in_channels_ch2_q0.read() ^ ap_const_lv8_80);
}

void yuv_filter_yuv2rgb::thread_E_fu_343_p2() {
    E_fu_343_p2 = (in_channels_ch3_q0.read() ^ ap_const_lv8_80);
}

void yuv_filter_yuv2rgb::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_ap_return_0() {
    ap_return_0 = in_width_read.read();
}

void yuv_filter_yuv2rgb::thread_ap_return_1() {
    ap_return_1 = in_height_read.read();
}

void yuv_filter_yuv2rgb::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void yuv_filter_yuv2rgb::thread_ap_sig_bdd_392() {
    ap_sig_bdd_392 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void yuv_filter_yuv2rgb::thread_ap_sig_bdd_92() {
    ap_sig_bdd_92 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void yuv_filter_yuv2rgb::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_bdd_92.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_ap_sig_cseq_ST_st9_fsm_2() {
    if (ap_sig_bdd_392.read()) {
        ap_sig_cseq_ST_st9_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_2 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_bound_fu_236_p0() {
    bound_fu_236_p0 =  (sc_lv<16>) (bound_fu_236_p00.read());
}

void yuv_filter_yuv2rgb::thread_bound_fu_236_p00() {
    bound_fu_236_p00 = esl_zext<32,16>(in_width_read.read());
}

void yuv_filter_yuv2rgb::thread_bound_fu_236_p1() {
    bound_fu_236_p1 =  (sc_lv<16>) (bound_fu_236_p10.read());
}

void yuv_filter_yuv2rgb::thread_bound_fu_236_p10() {
    bound_fu_236_p10 = esl_zext<32,16>(in_height_read.read());
}

void yuv_filter_yuv2rgb::thread_bound_fu_236_p2() {
    bound_fu_236_p2 = (!bound_fu_236_p0.read().is_01() || !bound_fu_236_p1.read().is_01())? sc_lv<32>(): sc_biguint<16>(bound_fu_236_p0.read()) * sc_biguint<16>(bound_fu_236_p1.read());
}

void yuv_filter_yuv2rgb::thread_exitcond_flatten_fu_242_p2() {
    exitcond_flatten_fu_242_p2 = (!indvar_flatten_reg_194.read().is_01() || !bound_reg_635.read().is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_194.read() == bound_reg_635.read());
}

void yuv_filter_yuv2rgb::thread_exitcond_fu_253_p2() {
    exitcond_fu_253_p2 = (!y_reg_216.read().is_01() || !in_height_read.read().is_01())? sc_lv<1>(): sc_lv<1>(y_reg_216.read() == in_height_read.read());
}

void yuv_filter_yuv2rgb::thread_icmp1_fu_588_p2() {
    icmp1_fu_588_p2 = (!tmp_4_reg_750.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_reg_750.read() == ap_const_lv2_1);
}

void yuv_filter_yuv2rgb::thread_icmp2_fu_562_p2() {
    icmp2_fu_562_p2 = (!tmp_8_reg_735.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): (sc_bigint<3>(tmp_8_reg_735.read()) > sc_bigint<3>(ap_const_lv3_0));
}

void yuv_filter_yuv2rgb::thread_icmp_fu_490_p2() {
    icmp_fu_490_p2 = (!tmp_1_reg_715.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_reg_715.read() == ap_const_lv2_1);
}

void yuv_filter_yuv2rgb::thread_in_channels_ch1_address0() {
    in_channels_ch1_address0 =  (sc_lv<22>) (tmp_10_fu_323_p1.read());
}

void yuv_filter_yuv2rgb::thread_in_channels_ch1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        in_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_in_channels_ch2_address0() {
    in_channels_ch2_address0 =  (sc_lv<22>) (tmp_10_reg_666.read());
}

void yuv_filter_yuv2rgb::thread_in_channels_ch2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read())) {
        in_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_in_channels_ch3_address0() {
    in_channels_ch3_address0 =  (sc_lv<22>) (tmp_10_reg_666.read());
}

void yuv_filter_yuv2rgb::thread_in_channels_ch3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read())) {
        in_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        in_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_indvar_flatten_next_fu_247_p2() {
    indvar_flatten_next_fu_247_p2 = (!indvar_flatten_reg_194.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(indvar_flatten_reg_194.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void yuv_filter_yuv2rgb::thread_out_channels_ch1_address0() {
    out_channels_ch1_address0 =  (sc_lv<22>) (ap_reg_ppstg_tmp_10_reg_666_pp0_it4.read());
}

void yuv_filter_yuv2rgb::thread_out_channels_ch1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read())) {
        out_channels_ch1_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch1_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_out_channels_ch1_d0() {
    out_channels_ch1_d0 = (!tmp_3_fu_503_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_3_fu_503_p2.read()[0].to_bool())? p_phitmp_fu_495_p3.read(): phitmp_reg_725.read());
}

void yuv_filter_yuv2rgb::thread_out_channels_ch1_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
          esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4.read(), ap_const_lv1_0)))) {
        out_channels_ch1_we0 = ap_const_logic_1;
    } else {
        out_channels_ch1_we0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_out_channels_ch2_address0() {
    out_channels_ch2_address0 =  (sc_lv<22>) (ap_reg_ppstg_tmp_10_reg_666_pp0_it5.read());
}

void yuv_filter_yuv2rgb::thread_out_channels_ch2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read())) {
        out_channels_ch2_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch2_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_out_channels_ch2_d0() {
    out_channels_ch2_d0 = (!tmp_6_fu_601_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_6_fu_601_p2.read()[0].to_bool())? p_phitmp2_fu_593_p3.read(): phitmp2_reg_760.read());
}

void yuv_filter_yuv2rgb::thread_out_channels_ch2_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()) && 
          esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it5.read(), ap_const_lv1_0)))) {
        out_channels_ch2_we0 = ap_const_logic_1;
    } else {
        out_channels_ch2_we0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_out_channels_ch3_address0() {
    out_channels_ch3_address0 =  (sc_lv<22>) (ap_reg_ppstg_tmp_10_reg_666_pp0_it4.read());
}

void yuv_filter_yuv2rgb::thread_out_channels_ch3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read())) {
        out_channels_ch3_ce0 = ap_const_logic_1;
    } else {
        out_channels_ch3_ce0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_out_channels_ch3_d0() {
    out_channels_ch3_d0 = (!tmp_9_fu_575_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_9_fu_575_p2.read()[0].to_bool())? p_phitmp3_fu_567_p3.read(): phitmp3_reg_745.read());
}

void yuv_filter_yuv2rgb::thread_out_channels_ch3_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
          esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4.read(), ap_const_lv1_0)))) {
        out_channels_ch3_we0 = ap_const_logic_1;
    } else {
        out_channels_ch3_we0 = ap_const_logic_0;
    }
}

void yuv_filter_yuv2rgb::thread_p_addr1_fu_317_p2() {
    p_addr1_fu_317_p2 = (!p_addr_fu_311_p2.read().is_01() || !tmp_trn_cast_fu_286_p1.read().is_01())? sc_lv<27>(): (sc_biguint<27>(p_addr_fu_311_p2.read()) + sc_biguint<27>(tmp_trn_cast_fu_286_p1.read()));
}

void yuv_filter_yuv2rgb::thread_p_addr_fu_311_p2() {
    p_addr_fu_311_p2 = (!p_shl9_cast_fu_296_p1.read().is_01() || !p_shl10_cast_fu_307_p1.read().is_01())? sc_lv<27>(): (sc_biguint<27>(p_shl9_cast_fu_296_p1.read()) + sc_biguint<27>(p_shl10_cast_fu_307_p1.read()));
}

void yuv_filter_yuv2rgb::thread_p_phitmp2_fu_593_p3() {
    p_phitmp2_fu_593_p3 = (!icmp1_fu_588_p2.read()[0].is_01())? sc_lv<8>(): ((icmp1_fu_588_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void yuv_filter_yuv2rgb::thread_p_phitmp3_fu_567_p3() {
    p_phitmp3_fu_567_p3 = (!icmp2_fu_562_p2.read()[0].is_01())? sc_lv<8>(): ((icmp2_fu_562_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void yuv_filter_yuv2rgb::thread_p_phitmp_fu_495_p3() {
    p_phitmp_fu_495_p3 = (!icmp_fu_490_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_fu_490_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void yuv_filter_yuv2rgb::thread_p_shl10_cast_fu_307_p1() {
    p_shl10_cast_fu_307_p1 = esl_zext<27,24>(tmp_7_fu_300_p3.read());
}

void yuv_filter_yuv2rgb::thread_p_shl1_cast_fu_443_p1() {
    p_shl1_cast_fu_443_p1 = esl_sext<18,10>(p_shl1_fu_436_p3.read());
}

void yuv_filter_yuv2rgb::thread_p_shl1_fu_436_p3() {
    p_shl1_fu_436_p3 = esl_concat<8,2>(D_reg_695.read(), ap_const_lv2_0);
}

void yuv_filter_yuv2rgb::thread_p_shl9_cast_fu_296_p1() {
    p_shl9_cast_fu_296_p1 = esl_zext<27,26>(tmp_fu_289_p3.read());
}

void yuv_filter_yuv2rgb::thread_p_shl_cast_fu_432_p1() {
    p_shl_cast_fu_432_p1 = esl_sext<19,17>(p_shl_fu_425_p3.read());
}

void yuv_filter_yuv2rgb::thread_p_shl_fu_425_p3() {
    p_shl_fu_425_p3 = esl_concat<8,9>(D_reg_695.read(), ap_const_lv9_0);
}

void yuv_filter_yuv2rgb::thread_tmp1_fu_420_p2() {
    tmp1_fu_420_p2 = (!tmp_24_reg_708.read().is_01() || !tmp_29_cast_fu_416_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_24_reg_708.read()) + sc_bigint<18>(tmp_29_cast_fu_416_p1.read()));
}

void yuv_filter_yuv2rgb::thread_tmp2_cast_fu_452_p1() {
    tmp2_cast_fu_452_p1 = esl_sext<19,18>(tmp2_fu_447_p2.read());
}

void yuv_filter_yuv2rgb::thread_tmp2_fu_447_p2() {
    tmp2_fu_447_p2 = (!p_shl1_cast_fu_443_p1.read().is_01() || !tmp_24_reg_708.read().is_01())? sc_lv<18>(): (sc_bigint<18>(p_shl1_cast_fu_443_p1.read()) + sc_bigint<18>(tmp_24_reg_708.read()));
}

void yuv_filter_yuv2rgb::thread_tmp_10_fu_323_p1() {
    tmp_10_fu_323_p1 = esl_zext<64,27>(p_addr1_fu_317_p2.read());
}

void yuv_filter_yuv2rgb::thread_tmp_22_fu_353_p0() {
    tmp_22_fu_353_p0 = C_fu_331_p2.read();
}

void yuv_filter_yuv2rgb::thread_tmp_22_fu_353_p2() {
    tmp_22_fu_353_p2 = (!tmp_22_fu_353_p0.read().is_01() || !ap_const_lv18_12A.is_01())? sc_lv<18>(): sc_bigint<9>(tmp_22_fu_353_p0.read()) * sc_biguint<18>(ap_const_lv18_12A);
}

void yuv_filter_yuv2rgb::thread_tmp_23_fu_371_p0() {
    tmp_23_fu_371_p0 = E_reg_702.read();
}

void yuv_filter_yuv2rgb::thread_tmp_23_fu_371_p2() {
    tmp_23_fu_371_p2 = (!tmp_23_fu_371_p0.read().is_01() || !ap_const_lv18_199.is_01())? sc_lv<18>(): sc_bigint<8>(tmp_23_fu_371_p0.read()) * sc_biguint<18>(ap_const_lv18_199);
}

void yuv_filter_yuv2rgb::thread_tmp_24_fu_359_p2() {
    tmp_24_fu_359_p2 = (!tmp_22_fu_353_p2.read().is_01() || !ap_const_lv18_80.is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_22_fu_353_p2.read()) + sc_biguint<18>(ap_const_lv18_80));
}

void yuv_filter_yuv2rgb::thread_tmp_25_fu_377_p2() {
    tmp_25_fu_377_p2 = (!tmp_23_fu_371_p2.read().is_01() || !tmp_24_reg_708.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_23_fu_371_p2.read()) + sc_bigint<18>(tmp_24_reg_708.read()));
}

void yuv_filter_yuv2rgb::thread_tmp_26_fu_519_p0() {
    tmp_26_fu_519_p0 = ap_reg_ppstg_D_reg_695_pp0_it4.read();
}

void yuv_filter_yuv2rgb::thread_tmp_26_fu_519_p2() {
    tmp_26_fu_519_p2 = (!tmp_26_fu_519_p0.read().is_01() || !ap_const_lv16_FF9C.is_01())? sc_lv<16>(): sc_bigint<8>(tmp_26_fu_519_p0.read()) * sc_bigint<16>(ap_const_lv16_FF9C);
}

void yuv_filter_yuv2rgb::thread_tmp_27_fu_410_p0() {
    tmp_27_fu_410_p0 = E_reg_702.read();
}

void yuv_filter_yuv2rgb::thread_tmp_27_fu_410_p2() {
    tmp_27_fu_410_p2 = (!tmp_27_fu_410_p0.read().is_01() || !ap_const_lv17_1FF30.is_01())? sc_lv<17>(): sc_bigint<8>(tmp_27_fu_410_p0.read()) * sc_bigint<17>(ap_const_lv17_1FF30);
}

void yuv_filter_yuv2rgb::thread_tmp_28_cast_fu_525_p1() {
    tmp_28_cast_fu_525_p1 = esl_sext<18,16>(tmp_26_fu_519_p2.read());
}

void yuv_filter_yuv2rgb::thread_tmp_28_fu_529_p2() {
    tmp_28_fu_529_p2 = (!tmp1_reg_730.read().is_01() || !tmp_28_cast_fu_525_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp1_reg_730.read()) + sc_bigint<18>(tmp_28_cast_fu_525_p1.read()));
}

void yuv_filter_yuv2rgb::thread_tmp_29_cast_fu_416_p1() {
    tmp_29_cast_fu_416_p1 = esl_sext<18,17>(tmp_27_fu_410_p2.read());
}

void yuv_filter_yuv2rgb::thread_tmp_29_fu_456_p2() {
    tmp_29_fu_456_p2 = (!tmp2_cast_fu_452_p1.read().is_01() || !p_shl_cast_fu_432_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(tmp2_cast_fu_452_p1.read()) + sc_bigint<19>(p_shl_cast_fu_432_p1.read()));
}

void yuv_filter_yuv2rgb::thread_tmp_3_fu_503_p2() {
    tmp_3_fu_503_p2 = (icmp_fu_490_p2.read() | tmp_2_reg_720.read());
}

void yuv_filter_yuv2rgb::thread_tmp_40_cast_fu_328_p1() {
    tmp_40_cast_fu_328_p1 = esl_zext<9,8>(Y_reg_680.read());
}

void yuv_filter_yuv2rgb::thread_tmp_6_fu_601_p2() {
    tmp_6_fu_601_p2 = (icmp1_fu_588_p2.read() | tmp_5_reg_755.read());
}

void yuv_filter_yuv2rgb::thread_tmp_7_fu_300_p3() {
    tmp_7_fu_300_p3 = esl_concat<16,8>(x_mid2_reg_654.read(), ap_const_lv8_0);
}

void yuv_filter_yuv2rgb::thread_tmp_9_fu_575_p2() {
    tmp_9_fu_575_p2 = (icmp2_fu_562_p2.read() | tmp_11_reg_740.read());
}

void yuv_filter_yuv2rgb::thread_tmp_fu_289_p3() {
    tmp_fu_289_p3 = esl_concat<16,10>(x_mid2_reg_654.read(), ap_const_lv10_0);
}

void yuv_filter_yuv2rgb::thread_tmp_trn_cast_fu_286_p1() {
    tmp_trn_cast_fu_286_p1 = esl_zext<27,16>(y_mid2_reg_649.read());
}

void yuv_filter_yuv2rgb::thread_x_mid2_fu_272_p3() {
    x_mid2_fu_272_p3 = (!exitcond_fu_253_p2.read()[0].is_01())? sc_lv<16>(): ((exitcond_fu_253_p2.read()[0].to_bool())? x_s_fu_266_p2.read(): x_phi_fu_209_p4.read());
}

void yuv_filter_yuv2rgb::thread_x_phi_fu_209_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_640.read(), ap_const_lv1_0))) {
        x_phi_fu_209_p4 = x_mid2_reg_654.read();
    } else {
        x_phi_fu_209_p4 = x_reg_205.read();
    }
}

void yuv_filter_yuv2rgb::thread_x_s_fu_266_p2() {
    x_s_fu_266_p2 = (!x_phi_fu_209_p4.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(x_phi_fu_209_p4.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void yuv_filter_yuv2rgb::thread_y_3_fu_280_p2() {
    y_3_fu_280_p2 = (!y_mid2_fu_258_p3.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(y_mid2_fu_258_p3.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void yuv_filter_yuv2rgb::thread_y_mid2_fu_258_p3() {
    y_mid2_fu_258_p3 = (!exitcond_fu_253_p2.read()[0].is_01())? sc_lv<16>(): ((exitcond_fu_253_p2.read()[0].to_bool())? ap_const_lv16_0: y_reg_216.read());
}

void yuv_filter_yuv2rgb::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten_fu_242_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten_fu_242_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_st9_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

