// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _yuv_filter_yuv2rgb_HH_
#define _yuv_filter_yuv2rgb_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct yuv_filter_yuv2rgb : public sc_module {
    // Port declarations 31
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<22> > in_channels_ch1_address0;
    sc_out< sc_logic > in_channels_ch1_ce0;
    sc_in< sc_lv<8> > in_channels_ch1_q0;
    sc_out< sc_lv<22> > in_channels_ch2_address0;
    sc_out< sc_logic > in_channels_ch2_ce0;
    sc_in< sc_lv<8> > in_channels_ch2_q0;
    sc_out< sc_lv<22> > in_channels_ch3_address0;
    sc_out< sc_logic > in_channels_ch3_ce0;
    sc_in< sc_lv<8> > in_channels_ch3_q0;
    sc_in< sc_lv<16> > in_width_read;
    sc_in< sc_lv<16> > in_height_read;
    sc_out< sc_lv<22> > out_channels_ch1_address0;
    sc_out< sc_logic > out_channels_ch1_ce0;
    sc_out< sc_logic > out_channels_ch1_we0;
    sc_out< sc_lv<8> > out_channels_ch1_d0;
    sc_out< sc_lv<22> > out_channels_ch2_address0;
    sc_out< sc_logic > out_channels_ch2_ce0;
    sc_out< sc_logic > out_channels_ch2_we0;
    sc_out< sc_lv<8> > out_channels_ch2_d0;
    sc_out< sc_lv<22> > out_channels_ch3_address0;
    sc_out< sc_logic > out_channels_ch3_ce0;
    sc_out< sc_logic > out_channels_ch3_we0;
    sc_out< sc_lv<8> > out_channels_ch3_d0;
    sc_out< sc_lv<16> > ap_return_0;
    sc_out< sc_lv<16> > ap_return_1;


    // Module declarations
    yuv_filter_yuv2rgb(sc_module_name name);
    SC_HAS_PROCESS(yuv_filter_yuv2rgb);

    ~yuv_filter_yuv2rgb();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_21;
    sc_signal< sc_lv<32> > indvar_flatten_reg_194;
    sc_signal< sc_lv<16> > x_reg_205;
    sc_signal< sc_lv<16> > y_reg_216;
    sc_signal< sc_lv<32> > bound_fu_236_p2;
    sc_signal< sc_lv<32> > bound_reg_635;
    sc_signal< sc_lv<1> > exitcond_flatten_fu_242_p2;
    sc_signal< sc_lv<1> > exitcond_flatten_reg_640;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_1;
    sc_signal< bool > ap_sig_bdd_92;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it5;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it6;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it3;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it4;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_flatten_reg_640_pp0_it5;
    sc_signal< sc_lv<32> > indvar_flatten_next_fu_247_p2;
    sc_signal< sc_lv<16> > y_mid2_fu_258_p3;
    sc_signal< sc_lv<16> > y_mid2_reg_649;
    sc_signal< sc_lv<16> > x_mid2_fu_272_p3;
    sc_signal< sc_lv<16> > x_mid2_reg_654;
    sc_signal< sc_lv<16> > y_3_fu_280_p2;
    sc_signal< sc_lv<64> > tmp_10_fu_323_p1;
    sc_signal< sc_lv<64> > tmp_10_reg_666;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_10_reg_666_pp0_it2;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_10_reg_666_pp0_it3;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_10_reg_666_pp0_it4;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_10_reg_666_pp0_it5;
    sc_signal< sc_lv<8> > Y_reg_680;
    sc_signal< sc_lv<8> > D_fu_337_p2;
    sc_signal< sc_lv<8> > D_reg_695;
    sc_signal< sc_lv<8> > ap_reg_ppstg_D_reg_695_pp0_it4;
    sc_signal< sc_lv<8> > E_fu_343_p2;
    sc_signal< sc_lv<8> > E_reg_702;
    sc_signal< sc_lv<18> > tmp_24_fu_359_p2;
    sc_signal< sc_lv<18> > tmp_24_reg_708;
    sc_signal< sc_lv<2> > tmp_1_reg_715;
    sc_signal< sc_lv<1> > tmp_2_reg_720;
    sc_signal< sc_lv<8> > phitmp_reg_725;
    sc_signal< sc_lv<18> > tmp1_fu_420_p2;
    sc_signal< sc_lv<18> > tmp1_reg_730;
    sc_signal< sc_lv<3> > tmp_8_reg_735;
    sc_signal< sc_lv<1> > tmp_11_reg_740;
    sc_signal< sc_lv<8> > phitmp3_reg_745;
    sc_signal< sc_lv<2> > tmp_4_reg_750;
    sc_signal< sc_lv<1> > tmp_5_reg_755;
    sc_signal< sc_lv<8> > phitmp2_reg_760;
    sc_signal< sc_lv<16> > x_phi_fu_209_p4;
    sc_signal< sc_lv<16> > bound_fu_236_p0;
    sc_signal< sc_lv<16> > bound_fu_236_p1;
    sc_signal< sc_lv<1> > exitcond_fu_253_p2;
    sc_signal< sc_lv<16> > x_s_fu_266_p2;
    sc_signal< sc_lv<26> > tmp_fu_289_p3;
    sc_signal< sc_lv<24> > tmp_7_fu_300_p3;
    sc_signal< sc_lv<27> > p_shl9_cast_fu_296_p1;
    sc_signal< sc_lv<27> > p_shl10_cast_fu_307_p1;
    sc_signal< sc_lv<27> > p_addr_fu_311_p2;
    sc_signal< sc_lv<27> > tmp_trn_cast_fu_286_p1;
    sc_signal< sc_lv<27> > p_addr1_fu_317_p2;
    sc_signal< sc_lv<9> > tmp_40_cast_fu_328_p1;
    sc_signal< sc_lv<9> > C_fu_331_p2;
    sc_signal< sc_lv<9> > tmp_22_fu_353_p0;
    sc_signal< sc_lv<18> > tmp_22_fu_353_p2;
    sc_signal< sc_lv<8> > tmp_23_fu_371_p0;
    sc_signal< sc_lv<18> > tmp_23_fu_371_p2;
    sc_signal< sc_lv<18> > tmp_25_fu_377_p2;
    sc_signal< sc_lv<8> > tmp_27_fu_410_p0;
    sc_signal< sc_lv<17> > tmp_27_fu_410_p2;
    sc_signal< sc_lv<18> > tmp_29_cast_fu_416_p1;
    sc_signal< sc_lv<17> > p_shl_fu_425_p3;
    sc_signal< sc_lv<10> > p_shl1_fu_436_p3;
    sc_signal< sc_lv<18> > p_shl1_cast_fu_443_p1;
    sc_signal< sc_lv<18> > tmp2_fu_447_p2;
    sc_signal< sc_lv<19> > tmp2_cast_fu_452_p1;
    sc_signal< sc_lv<19> > p_shl_cast_fu_432_p1;
    sc_signal< sc_lv<19> > tmp_29_fu_456_p2;
    sc_signal< sc_lv<1> > icmp_fu_490_p2;
    sc_signal< sc_lv<1> > tmp_3_fu_503_p2;
    sc_signal< sc_lv<8> > p_phitmp_fu_495_p3;
    sc_signal< sc_lv<8> > tmp_26_fu_519_p0;
    sc_signal< sc_lv<16> > tmp_26_fu_519_p2;
    sc_signal< sc_lv<18> > tmp_28_cast_fu_525_p1;
    sc_signal< sc_lv<18> > tmp_28_fu_529_p2;
    sc_signal< sc_lv<1> > icmp2_fu_562_p2;
    sc_signal< sc_lv<1> > tmp_9_fu_575_p2;
    sc_signal< sc_lv<8> > p_phitmp3_fu_567_p3;
    sc_signal< sc_lv<1> > icmp1_fu_588_p2;
    sc_signal< sc_lv<1> > tmp_6_fu_601_p2;
    sc_signal< sc_lv<8> > p_phitmp2_fu_593_p3;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_2;
    sc_signal< bool > ap_sig_bdd_392;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_lv<32> > bound_fu_236_p00;
    sc_signal< sc_lv<32> > bound_fu_236_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_1;
    static const sc_lv<3> ap_ST_st9_fsm_2;
    static const bool ap_true;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<16> ap_const_lv16_1;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<9> ap_const_lv9_1F0;
    static const sc_lv<8> ap_const_lv8_80;
    static const sc_lv<18> ap_const_lv18_12A;
    static const sc_lv<18> ap_const_lv18_80;
    static const sc_lv<18> ap_const_lv18_199;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<17> ap_const_lv17_1FF30;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<16> ap_const_lv16_FF9C;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_C_fu_331_p2();
    void thread_D_fu_337_p2();
    void thread_E_fu_343_p2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_sig_bdd_21();
    void thread_ap_sig_bdd_392();
    void thread_ap_sig_bdd_92();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_1();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st9_fsm_2();
    void thread_bound_fu_236_p0();
    void thread_bound_fu_236_p00();
    void thread_bound_fu_236_p1();
    void thread_bound_fu_236_p10();
    void thread_bound_fu_236_p2();
    void thread_exitcond_flatten_fu_242_p2();
    void thread_exitcond_fu_253_p2();
    void thread_icmp1_fu_588_p2();
    void thread_icmp2_fu_562_p2();
    void thread_icmp_fu_490_p2();
    void thread_in_channels_ch1_address0();
    void thread_in_channels_ch1_ce0();
    void thread_in_channels_ch2_address0();
    void thread_in_channels_ch2_ce0();
    void thread_in_channels_ch3_address0();
    void thread_in_channels_ch3_ce0();
    void thread_indvar_flatten_next_fu_247_p2();
    void thread_out_channels_ch1_address0();
    void thread_out_channels_ch1_ce0();
    void thread_out_channels_ch1_d0();
    void thread_out_channels_ch1_we0();
    void thread_out_channels_ch2_address0();
    void thread_out_channels_ch2_ce0();
    void thread_out_channels_ch2_d0();
    void thread_out_channels_ch2_we0();
    void thread_out_channels_ch3_address0();
    void thread_out_channels_ch3_ce0();
    void thread_out_channels_ch3_d0();
    void thread_out_channels_ch3_we0();
    void thread_p_addr1_fu_317_p2();
    void thread_p_addr_fu_311_p2();
    void thread_p_phitmp2_fu_593_p3();
    void thread_p_phitmp3_fu_567_p3();
    void thread_p_phitmp_fu_495_p3();
    void thread_p_shl10_cast_fu_307_p1();
    void thread_p_shl1_cast_fu_443_p1();
    void thread_p_shl1_fu_436_p3();
    void thread_p_shl9_cast_fu_296_p1();
    void thread_p_shl_cast_fu_432_p1();
    void thread_p_shl_fu_425_p3();
    void thread_tmp1_fu_420_p2();
    void thread_tmp2_cast_fu_452_p1();
    void thread_tmp2_fu_447_p2();
    void thread_tmp_10_fu_323_p1();
    void thread_tmp_22_fu_353_p0();
    void thread_tmp_22_fu_353_p2();
    void thread_tmp_23_fu_371_p0();
    void thread_tmp_23_fu_371_p2();
    void thread_tmp_24_fu_359_p2();
    void thread_tmp_25_fu_377_p2();
    void thread_tmp_26_fu_519_p0();
    void thread_tmp_26_fu_519_p2();
    void thread_tmp_27_fu_410_p0();
    void thread_tmp_27_fu_410_p2();
    void thread_tmp_28_cast_fu_525_p1();
    void thread_tmp_28_fu_529_p2();
    void thread_tmp_29_cast_fu_416_p1();
    void thread_tmp_29_fu_456_p2();
    void thread_tmp_3_fu_503_p2();
    void thread_tmp_40_cast_fu_328_p1();
    void thread_tmp_6_fu_601_p2();
    void thread_tmp_7_fu_300_p3();
    void thread_tmp_9_fu_575_p2();
    void thread_tmp_fu_289_p3();
    void thread_tmp_trn_cast_fu_286_p1();
    void thread_x_mid2_fu_272_p3();
    void thread_x_phi_fu_209_p4();
    void thread_x_s_fu_266_p2();
    void thread_y_3_fu_280_p2();
    void thread_y_mid2_fu_258_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
