// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmotorctrl.h"

extern XMotorctrl_Config XMotorctrl_ConfigTable[];

XMotorctrl_Config *XMotorctrl_LookupConfig(u16 DeviceId) {
	XMotorctrl_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMOTORCTRL_NUM_INSTANCES; Index++) {
		if (XMotorctrl_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMotorctrl_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMotorctrl_Initialize(XMotorctrl *InstancePtr, u16 DeviceId) {
	XMotorctrl_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMotorctrl_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMotorctrl_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

